# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :release do
    #cert(
    #  development: true,
    #  username: "pmuthuraju@ztech.io",
    #  keychain_password: "soaadmin"
    #)
    match(app_identifier: "com.pridfastlane.test.app1", username: "pmuthuraju@ztech.io")
    build_app(scheme: "test")
  end
end
