# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :release do
    #cert(
    #  development: true,
    #  username: "pmuthuraju@ztech.io",
    #  keychain_password: "soaadmin"
    #)
    automatic_code_signing(
      use_automatic_signing: true,
      bundle_identifier: "com.pridfastlane.test.app1"
    )
    build_ios_app(
    #  export_team_id: "NW4UKN7633",
    #  export_options: {
    #    provisioningProfiles: { 
    #      "com.pridfastlane.test.app1" => "com.pridfastlane.test.app1",
    #    }
    #  }
    )
    #build_app()
  end
end
