# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :release do
    sigh(
      app_identifier: "com.pridfastlane.test.app1",
      devlopment: true,
      username: "pmuthuraju@ztech.io",
      provisioning_name: "match Development com.pridfastlane.test.app1",
      readonly: true
    )
    #match(type: "appstore", app_identifier: "com.pridfastlane.test.app1", readonly: is_ci)
    gym
  end
end
